### PR TITLE
Project NYT Clone (Week 1 - Microverse)

### PR DESCRIPTION
**Pull request by enionsouza**
There are some features that still must be added to the project.
- [x] Header
- [x] Aside element
- [x] Fixed Navbar at the top
- [x] Most of the main content
- [x] Some details at the beginning and end of the main content
- [x] Footer

### CODE REVIEW

**Comment by enionsouza** [comment]
Please consider that the `<iframe>` element was recommended by YouTube.com

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @enionsouza  :wave: 

It's impressive to see how well you've done considering it's your first project at Microverse 👍 👏
However, there are still some changes to be made before your project can be approved.

## REQUIRED

* [ ] Kindly make sure all the linter checks pass.
* [ ] The screenshot in your README is not coming up.
* [ ] You're yet to add the footer
* [ ]  Elements on the page are to be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). You only made use of float and grid.

### "As described in the [Code review limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by enionsouza** [comment]
The project for my first week at Microverse is finished!
*This is my second code review request.*

The required actions stated by @ElijahTobs have been completed:
* [x] Kindly make sure all the linter checks pass.
* [x] The screenshot in your README is not coming up.
* [x] You're yet to add the footer
* [x]  Elements on the page are to be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/))

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @enionsouza! You have done a great job. Your webpage is extremely identical to the original. Nice work of addressing all the issues pointed out by the previous TSE. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next project.

**Comment by enionsouza** [comment]
Thank you very much for your review, Mr @smcommits :pray: 
It was a lot of hard work to achieve this!

**Pull request merged**
